export const enumSteps = {
  home: 0,
  personalData: 1,
  contact: 2,
  packages: 3,
  extraMeals: 4,
  finalReview: 5,
  formPayment: 6,
  success: 7,
};

export const initialValues = {
  registrationDate: '',
  totalPrice: '',
  observation: '',
  manualRegistration: '',
  personalInformation: {
    name: '',
    birthday: '',
    cpf: '',
    rg: '',
    rgShipper: '',
    rgShipperState: '',
    gender: '',
  },
  contact: {
    cellPhone: '',
    email: '',
    isWhatsApp: '',
    church: '',
    car: '',
    numberVacancies: '',
    needRide: '',
    rideObservation: '',
    hasAllergy: '',
    allergy: '',
    hasAggregate: '',
    aggregate: '',
  },
  package: {
    accomodation: {
      id: '',
      name: '',
      subAccomodation: '',
    },
    discountCoupon: '',
    discountValue: '',
    transportation: '',
    food: '',
    price: '',
    finalPrice: '',
    title: '',
  },
  extraMeals: {
    someFood: '',
    totalPrice: '',
  },
  formPayment: {
    formPayment: '',
  },
};

export const packages = [
  'PACOTE 1 - HOSPEDAGEM INDIVIDUAL EM SALA COLETIVA COM ÔNIBUS',
  'PACOTE 2 - HOSPEDAGEM INDIVIDUAL EM SALA COLETIVA SEM ÔNIBUS',
  'PACOTE 3 - HOSPEDAGEM INDIVIDUAL EM SALA COLETIVA COM ÔNIBUS',
  'PACOTE 4 - HOSPEDAGEM INDIVIDUAL EM SALA COLETIVA SEM ÔNIBUS',
  'PACOTE 5 - HOSPEDAGEM FAMÍLIA EM SALA INDIVIDUAL COM ÔNIBUS',
  'PACOTE 6 - HOSPEDAGEM FAMÍLIA EM SALA INDIVIDUAL SEM ÔNIBUS',
  'PACOTE 7 - HOSPEDAGEM FAMÍLIA EM SALA INDIVIDUAL COM ÔNIBUS',
  'PACOTE 8 - HOSPEDAGEM FAMÍLIA EM SALA INDIVIDUAL SEM ÔNIBUS',
  'PACOTE 9 - HOSPEDAGEM INDIVIDUAL OU FAMÍLIA EM BARRACAS (CAMPING) SEM ÔNIBUS',
  'PACOTE 10 - HOSPEDAGEM INDIVIDUAL OU FAMÍLIA EM BARRACAS (CAMPING) SEM ÔNIBUS',
  'PACOTE 11 - HOSPEDAGEM INDIVIDUAL COM ÔNIBUS',
  'PACOTE 12 - HOSPEDAGEM INDIVIDUAL SEM ÔNIBUS',
  'PACOTE 13 - HOSPEDAGEM EXTERNA COM ÔNIBUS',
  'PACOTE 14 - HOSPEDAGEM EXTERNA SEM ÔNIBUS',
  'PACOTE 15 - ASSISTIR O CULTO',
];
