const rgShipper = [
  { value: 'SDS', label: 'SDS - Secretaria de Defesa Social' },
  { value: 'SSP', label: 'SSP - Secretaria de Segurança Pública' },
  { value: 'SSPDS', label: 'SSPDS - Secretaria de Segurança Pública e Defesa Social' },
  { value: 'SEDS', label: 'SEDS - Secretaria de Estado de Defesa Social' },
  { value: 'DPF', label: 'DPF - Departamento de Polícia Federal' },
  { value: 'SSPC', label: 'SSPC - Secretaria de Segurança Pública e Cidadania' },
  { value: 'SSPT', label: 'SSPT - Secretaria de Segurança Pública e Trânsito' },
  { value: 'DETRAN', label: 'DETRAN - Departamento Estadual de Trânsito' },
  { value: 'SSJ', label: 'SSJ - Secretaria de Segurança e Justiça' },
  { value: 'SSPPS', label: 'SSPPS - Secretaria de Segurança Pública e Polícia Social' },
  { value: 'SESP', label: 'SESP - Secretaria de Estado de Segurança Pública' },
];

const issuingState = [
  { value: 'AC', label: 'AC' },
  { value: 'AL', label: 'AL' },
  { value: 'AP', label: 'AP' },
  { value: 'AM', label: 'AM' },
  { value: 'BA', label: 'BA' },
  { value: 'CE', label: 'CE' },
  { value: 'DF', label: 'DF' },
  { value: 'ES', label: 'ES' },
  { value: 'GO', label: 'GO' },
  { value: 'MA', label: 'MA' },
  { value: 'MT', label: 'MT' },
  { value: 'MS', label: 'MS' },
  { value: 'MG', label: 'MG' },
  { value: 'PA', label: 'PA' },
  { value: 'PB', label: 'PB' },
  { value: 'PR', label: 'PR' },
  { value: 'PE', label: 'PE' },
  { value: 'PI', label: 'PI' },
  { value: 'RJ', label: 'RJ' },
  { value: 'RN', label: 'RN' },
  { value: 'RS', label: 'RS' },
  { value: 'RO', label: 'RO' },
  { value: 'RR', label: 'RR' },
  { value: 'SC', label: 'SC' },
  { value: 'SP', label: 'SP' },
  { value: 'SE', label: 'SE' },
  { value: 'TO', label: 'TO' },
];

export { rgShipper, issuingState };
