export const enumSteps = {
  home: 0,
  personalData: 1,
  contact: 2,
  packages: 3,
  finalReview: 4,
  beforePayment: 5,
  formPayment: 6,
  success: 7,
};

export const initialValues = [
  {
    registrationDate: '',
    totalPrice: '',
    manualRegistration: '',
    personalInformation: {
      name: '',
      birthday: '',
      legalGuardianName: '',
      legalGuardianCpf: '',
      legalGuardianCellPhone: '',
      cpf: '',
      rg: '',
      rgShipper: '',
      rgShipperState: '',
      gender: '',
    },
    contact: {
      cellPhone: '',
      email: '',
      isWhatsApp: '',
      church: '',
      car: '',
      numberVacancies: '',
      needRide: '',
      rideObservation: '',
      hasAllergy: '',
      allergy: '',
      hasAggregate: '',
      aggregate: '',
    },
    package: {
      accomodation: {
        id: '',
        price: '',
      },
      accomodationName: '',
      transportation: {
        id: '',
        price: '',
      },
      transportationName: '',
      food: {
        id: '',
        price: '',
      },
      foodName: '',
      price: '',
      finalPrice: '',
    },
    extraMeals: {
      someFood: '',
      totalPrice: '',
      extraMeals: [''],
    },
    formPayment: '',
  },
];

export const rgShipper = [
  { value: 'SDS', label: 'SDS - Secretaria de Defesa Social' },
  { value: 'SSP', label: 'SSP - Secretaria de Segurança Pública' },
  { value: 'SSPDS', label: 'SSPDS - Secretaria de Segurança Pública e Defesa Social' },
  { value: 'SEDS', label: 'SEDS - Secretaria de Estado de Defesa Social' },
  { value: 'DPF', label: 'DPF - Departamento de Polícia Federal' },
  { value: 'SSPC', label: 'SSPC - Secretaria de Segurança Pública e Cidadania' },
  { value: 'SSPT', label: 'SSPT - Secretaria de Segurança Pública e Trânsito' },
  { value: 'DETRAN', label: 'DETRAN - Departamento Estadual de Trânsito' },
  { value: 'SSJ', label: 'SSJ - Secretaria de Segurança e Justiça' },
  { value: 'SSPPS', label: 'SSPPS - Secretaria de Segurança Pública e Polícia Social' },
  { value: 'SESP', label: 'SESP - Secretaria de Estado de Segurança Pública' },
  { value: 'MEX', label: 'MEX - Ministério do Exército' },
  { value: 'MAE', label: 'MAE - Ministério da Aeronáutica' },
  { value: 'MMA', label: 'MMA - Ministério da Marinha' },
  { value: 'Outro', label: 'Outro' },
];

export const issuingState = [
  { value: 'AC', label: 'AC' },
  { value: 'AL', label: 'AL' },
  { value: 'AP', label: 'AP' },
  { value: 'AM', label: 'AM' },
  { value: 'BA', label: 'BA' },
  { value: 'CE', label: 'CE' },
  { value: 'DF', label: 'DF' },
  { value: 'ES', label: 'ES' },
  { value: 'GO', label: 'GO' },
  { value: 'MA', label: 'MA' },
  { value: 'MT', label: 'MT' },
  { value: 'MS', label: 'MS' },
  { value: 'MG', label: 'MG' },
  { value: 'PA', label: 'PA' },
  { value: 'PB', label: 'PB' },
  { value: 'PR', label: 'PR' },
  { value: 'PE', label: 'PE' },
  { value: 'PI', label: 'PI' },
  { value: 'RJ', label: 'RJ' },
  { value: 'RN', label: 'RN' },
  { value: 'RS', label: 'RS' },
  { value: 'RO', label: 'RO' },
  { value: 'RR', label: 'RR' },
  { value: 'SC', label: 'SC' },
  { value: 'SP', label: 'SP' },
  { value: 'SE', label: 'SE' },
  { value: 'TO', label: 'TO' },
];

export const food = [
  {
    value: 'Alimentação Completa',
    label: 'Alimentação Completa',
  },
  { value: 'Sem Alimentação', label: 'Sem Alimentação' },
];

export const mealOptions = [
  { day: 'Sábado', name: 'Sábado - almoço', price: 26, checkboxMargin: '' },
  { day: 'Sábado', name: 'Sábado - jantar', price: 26, checkboxMargin: '' },
  { day: 'Domingo', name: 'Domingo - café da manhã', price: 23, checkboxMargin: 'mb-2' },
  { day: 'Domingo', name: 'Domingo - almoço', price: 26, checkboxMargin: 'mb-2' },
  { day: 'Domingo', name: 'Domingo - jantar', price: 26, checkboxMargin: '' },
  { day: 'Segunda', name: 'Segunda - café da manhã', price: 23, checkboxMargin: 'mb-2' },
  { day: 'Segunda', name: 'Segunda - almoço', price: 26, checkboxMargin: 'mb-2' },
  { day: 'Segunda', name: 'Segunda - jantar', price: 26, checkboxMargin: '' },
  { day: 'Terça', name: 'Terça - café da manhã', price: 23, checkboxMargin: 'mb-2' },
  { day: 'Terça', name: 'Terça - almoço', price: 26, checkboxMargin: 'mb-2' },
  { day: 'Terça', name: 'Terça - jantar', price: 26, checkboxMargin: '' },
  { day: 'Quarta', name: 'Quarta - café da manhã', price: 23, checkboxMargin: '' },
];

export const TABLE_HEADERS = [
  'ID',
  'Nome',
  'Organização',
  'Experiência nas Inscrições',
  'Alimentação',
  'Programação',
  'Estrutura Física',
  'Acolhimento',
  'Probabilidade de Volta',
  'Campo Aberto',
];

export const MAX_SIZE_CAMPERS = 1000;

export const FOOD_NAME_OPTIONS = [
  { label: 'Com Alimentação', value: 'Alimentação Completa' },
  { label: 'Sem Alimentação', value: 'Sem Alimentação' },
];

export const CREW_OPTIONS = [
  { value: 'Logística', label: 'Logística' },
  { value: 'Credenciamento', label: 'Credenciamento' },
  { value: 'Programação', label: 'Programação' },
  { value: 'Cozinha', label: 'Cozinha' },
  { value: 'Cantina', label: 'Cantina' },
  { value: 'Sistema', label: 'Sistema' },
  { value: 'Financeiro', label: 'Financeiro' },
  { value: 'Mídia', label: 'Mídia' },
  { value: 'Departamento Infantil', label: 'Departamento Infantil' },
  { value: 'Médica', label: 'Médica' },
  { value: '', label: 'Nenhum' },
];

export const iconsOptions = [
  { value: 'calendar', label: 'Calendário' },
  { value: 'close', label: 'Circulo com X' },
  { value: 'arrow-down-double', label: 'Seta dupla pra baixo' },
  { value: 'arrow-right', label: 'Seta pra direita' },
  { value: 'arrow-left', label: 'Seta pra esquerda' },
  { value: 'arrow-top', label: 'Seta pra direita' },
  { value: 'simple-arrow', label: 'Seta simples' },
  { value: 'selected', label: 'Selecionado' },
  { value: 'error', label: 'Erro' },
  { value: 'filter', label: 'Filtro' },
  { value: 'edit', label: 'Editar' },
  { value: 'delete', label: 'Deletar' },
  { value: 'sort', label: 'Ordenar' },
  { value: 'person', label: 'Pessoa' },
  { value: 'add-person', label: 'Adicionar Pessoa' },
  { value: 'excel', label: 'Excel' },
  { value: 'food', label: 'Comida' },
  { value: 'money', label: 'Dinheiro' },
  { value: 'discount', label: 'Desconto' },
  { value: 'checked', label: 'Checado' },
  { value: 'not-checked', label: 'Não Checado' },
  { value: 'ride', label: 'Carro' },
  { value: 'whatsapp', label: 'Whatsapp' },
  { value: 'message', label: 'Mensagem' },
  { value: 'share', label: 'Compartilhar' },
  { value: 'logout', label: 'Logout' },
  { value: 'settings', label: 'Configurações' },
  { value: 'logs', label: 'Logs' },
  { value: 'roles', label: 'Cargos' },
  { value: 'danger', label: 'Perigo' },
  { value: 'checkin', label: 'Checkin' },
  { value: 'aggregate', label: 'Agregados' },
  { value: 'm-glass', label: 'Lupa' },
  { value: 'camp', label: 'Camping' },
  { value: 'feedback', label: 'Feedback' },
  { value: 'info', label: 'Informação' },
  { value: 'refresh', label: 'Recarregar' },
  { value: 'warn', label: 'Alerta' },
  { value: 'plus', label: 'Mais' },
  { value: 'rooms', label: 'Quartos' },
  { value: 'chart', label: 'Gráfico' },
  { value: 'question', label: 'Pergunta' },
  { value: 'form-context', label: 'Construção' },
  { value: 'cart', label: 'Carrinho de Compras' },
  { value: 'rounded-question', label: 'Pergunta Circulada' },
  { value: 'simple-pin', label: 'Marcador Simples' },
  { value: 'location-pin', label: 'Marcador de Localização' },
  { value: 'credit-card', label: 'Cartão de Crédito' },
  { value: 'clock', label: 'Relógio' },
  { value: 'phone', label: 'Telefone' },
  { value: 'family', label: 'Família' },
  { value: 'simple-info', label: 'Informação Simples' },
  { value: 'form', label: 'Formulário' },
  { value: 'wristband', label: 'Pulseira' },
  { value: 'team', label: 'Time' },
]