export const products = [
  {
    id: 'host-college-collective',
    name: 'Colégio Quarto Coletivo',
    price: 0,
    description: 'Quartos coletivos, separados por idade',
    category: 'Hospedagem',
  },
  {
    id: 'host-college-family',
    name: 'Colégio Quarto Família',
    price: 0,
    description: 'Quartos separados para cada família',
    category: 'Hospedagem',
  },
  {
    id: 'host-college-camping',
    name: 'Colégio Camping',
    price: 0,
    description: 'Área destinada para quem vai acampar de barraca (barraca por sua conta)',
    category: 'Hospedagem',
  },
  {
    id: 'host-seminario',
    name: 'Seminário',
    price: 500,
    description: 'Quarto do seminário são josé',
    category: 'Hospedagem',
  },
  {
    id: 'host-external',
    name: 'Externo',
    price: 0,
    description: 'Qualquer hospedagem que não seja colégio ou seminário, por sua conta',
    category: 'Hospedagem',
  },
  {
    id: 'bus-yes',
    name: 'Com Ônibus',
    price: 200,
    description: 'Ônibus disponibilizado pela igreja',
    category: 'Transporte',
  },
  {
    id: 'bus-no',
    name: 'Sem Ônibus',
    price: 0,
    description: 'Qualquer transporte que não seja no ônibus da igreja, por sua conta',
    category: 'Transporte',
  },
  {
    id: 'food-complete',
    name: 'Alimentação Completa (Café da manhã, Almoço e Jantar)',
    price: 300,
    description: 'Café da manhã, almoço e jantar inclusos',
    category: 'Alimentação',
  },
  {
    id: 'food-external',
    name: 'Alimentação Parcial (Almoço e Jantar)',
    price: 240,
    description:
      'Apenas almoço e jantar. Café da manhã não incluso, destinado para quem vai ficar em hotéis que normalmente já inclui café da manhã.',
    category: 'Alimentação',
  },
];
